print("Hello, What is your name?")
myname = input()
print(' Welcome,' + myname)
print("What type of character would you like to be?")
print("Dwarf")
print("Giant")
print("Knight")
print("Royalty")
character = input()
print('You have chosen,' + character)
print("Both Magic and Attack points must add up to 100. Choose wisely.")
print("How many magic points will you add?")
Magic = input()
print('You have selected,' + Magic)
print("How many attack points will you add?")
Attack = input()
print('You have selected,' + Attack)
print("Welcome To The Dungeon")
print(" Click to Begin Quest!")
